---

- name: Set app dir permissions
  file:
    path: "{{ suitecrm_dest }}"
    owner: "{{ suitecrm_apache_user }}"
    group: "{{ suitecrm_apache_group }}"
    recurse: yes

- name: Set cache permissions
  file:
    path: "{{ suitecrm_dest }}/cache"
    owner: "{{ suitecrm_apache_user }}"
    group: "{{ suitecrm_apache_group }}"
    mode: 0777
    state: directory

- name: "Copy config_si.php to SuiteCRM root"
  when: suitecrm_install_from_scratch
  template:
    src: "config_si.php.j2"
    dest: "{{ suitecrm_dest }}/config_si.php"
    owner: "{{ suitecrm_apache_user }}"
    group: "{{ suitecrm_apache_group }}"
    mode: 0644

- name: Delete .htaccess if present
  file:
    path: "{{ suitecrm_dest }}/.htaccess"
    state: absent

- name: Install SuiteCRM
  when: suitecrm_install_from_scratch
  shell: php -r "\$_SERVER['HTTP_HOST'] = 'localhost'; \$_SERVER['REQUEST_URI'] = 'install.php';\$_REQUEST = array('goto' => 'SilentInstall', 'cli' => true);require_once 'install.php';";
  args:
    chdir: "{{ suitecrm_dest }}"
    creates: "{{ suitecrm_dest }}/config.php"

- name: Set config_override.php permissions
  file:
    path: "{{ suitecrm_dest }}/config_override.php"
    owner: "{{ suitecrm_apache_user }}"
    group: "{{ suitecrm_apache_group }}"
    mode: 0666

- name: Ensure cache/ permissions
  file:
    path: "{{ suitecrm_dest }}/cache"
    state: directory
    owner: "{{ suitecrm_apache_user }}"
    group: "{{ suitecrm_apache_group }}"
    mode: 0755
    recurse: yes

- import_tasks: tasks/translations.yml
  when: suitecrm_install_translations

- name: Set other directories permissions
  file:
    path: "{{ suitecrm_dest }}/{{ item }}"
    owner: "{{ suitecrm_apache_user }}"
    group: "{{ suitecrm_apache_group }}"
    mode: 0775
    state: directory
    recurse: yes
  with_items:
    - upgrades
    - update
    - upload
    - themes
    - custom

- import_tasks: tasks/composer_install.yml
  when: suitecrm_composer_install
