---

- name: "Translations: Generate random temp directory"
  command: mktemp -d "{{ suitecrm_translations_temp_directory_mask }}"
  changed_when: false
  register: suitecrm_translations_temp_dir
  become: no

- name: "Translations: Adjust random temp directory permissions"
  file:
    path: "{{ suitecrm_translations_temp_dir.stdout }}"
    mode: '0755'
  become: no
  changed_when: false

- name: "Translations: Downloading zip file"
  get_url:
    url: "{{ suitecrm_translations_file }}"
    dest: "{{ suitecrm_translations_temp_dir.stdout }}/suitecrmtranslations.zip"
    mode: 0660

- name: "Translations: Installing unzip app if not already present"
  apt:
    name: unzip
    state: present
    force_apt_get: yes
    update_cache: yes

- name: "Translations: unzip file"
  unarchive:
    src: "{{ suitecrm_translations_temp_dir.stdout }}/suitecrmtranslations.zip"
    dest: "{{ suitecrm_translations_temp_dir.stdout }}"
    remote_src: True

- name: "Translations: copy translations files"
  command: "cp -r {{ suitecrm_translations_temp_dir.stdout }}/{{ item }} {{ suitecrm_dest }}"
  with_items:
     - include
     - install
     - modules
     - upgrade
